name: prefman
description: A Structured Way to manage App Prefernces
version: 0.2.0
author: aligator.ir@gmail.com
homepage: https://github.com/ali2236/prefman

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter