name: prefman
description: A better way to manage App Preferences using persistant variables in a Structured Way.
version: 0.2.3
homepage: https://github.com/ali2236/prefman

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter